using Foxy.Params.SourceGenerator.Data;
using Foxy.Params.SourceGenerator.Helpers;
using Foxy.Params.SourceGenerator.NewData;

namespace Foxy.Params.SourceGenerator.Rendering;

internal class SourceFileRenderer : RendererBase<SourceBuilder>
{
    public static readonly SourceFileRenderer Instance = new();

    public override void Render(SuccessfulParamsGroupCandidateV2 element, SourceBuilder output)
    {
        output.AutoGeneratedComment();
        output.AppendLine();
        output.NullableEnable();
        output.AppendLine();
        element.TypeInfo.ExecuteRenderer(this, output);
        output.StartBlock();
        for (int i = 0; i < element.ParamCanditates.Count; i++)
        {
            if(i > 0)
            {
                output.AppendLine();
            }
            element.ParamCanditates[i].ExecuteRenderer(this, output);
        }
        output.EndBlock();
    }



    public override void Render(NamespaceElement element, SourceBuilder output)
    {
        element.Parent.ExecuteRenderer(this, output);
        output.Append('.');
        output.Append(element.Name);
    }
}
