using Foxy.Params.SourceGenerator.Data;
using Foxy.Params.SourceGenerator.Helpers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Foxy.Params.SourceGenerator.SourceGenerator
{
    internal class OverridesGenerator
    {
        private readonly SourceBuilder _sourceBuilder;
        private readonly INamedTypeSymbol _typeInfo;
        private readonly IEnumerable<SuccessfulParamsCandidate> _paramsCandidates;
        private readonly int _maxOverridesMax;

        public OverridesGenerator(INamedTypeSymbol typeInfo, IEnumerable<SuccessfulParamsCandidate> paramsCandidates)
        {
            _sourceBuilder = new SourceBuilder();
            _typeInfo = typeInfo ?? throw new ArgumentNullException(nameof(typeInfo));
            _paramsCandidates = paramsCandidates ?? throw new ArgumentNullException(nameof(paramsCandidates));
            _maxOverridesMax = paramsCandidates.Max(e => e.MaxOverrides);
        }

        public SourceText Execute()
        {
            _sourceBuilder.Clear();
            _sourceBuilder.AppendTrivias(
                AutoGeneratedComment(),
                CarriageReturnLineFeed,
                NullableEnable(),
                CarriageReturnLineFeed);
            GenerateNamespace();

            return SourceText.From(_sourceBuilder.ToString(), Encoding.UTF8);
        }

        private static SyntaxTrivia AutoGeneratedComment()
        {
            return Comment("// <auto-generated />");
        }

        private static SyntaxTrivia NullableEnable()
        {
            return Trivia(
                NullableDirectiveTrivia(
                    Token(TriviaList(Space), SyntaxKind.EnableKeyword, TriviaList()),
                    true));
        }

        private void GenerateNamespace()
        {
            AddNamespace(_sourceBuilder, _typeInfo);

            GeneratePartialClass();
            GenerateArgumentsClasses();

            AddNamespaceCloseBlock(_sourceBuilder, _typeInfo);
        }

        private void GeneratePartialClass()
        {
            var nestLevel = CreateClasses(_typeInfo, _sourceBuilder);

            foreach (var paramsCandidate in _paramsCandidates)
            {
                var data = new DerivedData(paramsCandidate);

                for (int n = 1; n <= paramsCandidate.MaxOverrides; n++)
                {
                    if (n > 1)
                    {
                        _sourceBuilder.AppendLine();
                    }

                    GenerateMethodOverrideWithNArgs(data, n);
                }

                GenerateOverrideWithParamsParameter(paramsCandidate, data);
            }

            CloseTimes(_sourceBuilder, nestLevel);
        }

        private static int CreateClasses(INamedTypeSymbol? typeInfo, SourceBuilder sb)
        {
            var items = SemanticHelpers.GetTypeHierarchy(typeInfo);
            foreach (var item in items)
            {
                sb.Class(item.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat));
            }

            return items.Count;
        }

        private static void CloseTimes(SourceBuilder sb, int nestLevel)
        {
            for (int i = 0; i < nestLevel; i++)
            {
                sb.CloseBlock();
            }
        }

        private void GenerateMethodOverrideWithNArgs(DerivedData data, int argsCount)
        {
            var variableArguments = data.FixArguments.Concat(
                Enumerable.Range(0, argsCount).Select(j => $"{data.SpanArgumentType} {data.ArgName}{j}"));
            GenerateMethodHeaderWithArguments(data, variableArguments);
            GenerateBodyForOverrideWithNArgs(data, argsCount);
            _sourceBuilder.CloseBlock();
        }

        private void GenerateMethodHeaderWithArguments(DerivedData data, IEnumerable<string> arguments)
        {
            _sourceBuilder.Method(
                data.MethodName,
                arguments,
                data.IsStatic,
                data.ReturnType,
                data.TypeArguments,
                data.TypeConstraints);
        }

        private void GenerateBodyForOverrideWithNArgs(DerivedData data, int argsCount)
        {
            GenerateArgumentsVariable(data, argsCount);
            GenerateSpanVariableForInlineArray(data, argsCount);
            GenerateCallOriginalMethod(data);
        }


        /// <summary>
        /// var {argsSpan} = global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref {arg}.arg0, {argsCount});
        /// </summary>
        private void GenerateSpanVariableForInlineArray(DerivedData data, int argsCount)
        {
            var variableDeclaration = SimpleVarDeclaration(
                VariableDeclarator(
                    Identifier(data.ArgNameSpan),
                    null,
                    EqualsValueClause(CallCreateReadOnlySpan(data.ArgName, argsCount))));
            _sourceBuilder.AppendBlockLine(variableDeclaration);
        }

        /// <summary>
        /// global::System.Runtime.InteropServices.MemoryMarshal.CreateReadOnlySpan(ref args.arg0, 1)
        /// </summary>
        private ExpressionSyntax CallCreateReadOnlySpan(string argName, int argsCount)
        {
            return InvocationExpression(
                GlobalMemberAccessChain(["System", "Runtime", "InteropServices", "MemoryMarshal", "CreateReadOnlySpan"]),
                Arguments([
                    QualifiedArgument(MemberAccessChain([argName, "arg0"]), SyntaxKind.RefKeyword),
                    Argument(SimpleLiteral(argsCount))
                    ])
                );
        }

        /// <summary>
        /// {intValue}
        /// </summary>
        private static LiteralExpressionSyntax SimpleLiteral(int value)
        {
            return LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(value));
        }

        private void GenerateArgumentsVariable(DerivedData data, int argsCount)
        {
            _sourceBuilder.AppendLine($"var {data.ArgName} = new Arguments{argsCount}<{data.SpanArgumentType}>({string.Join(", ", Enumerable.Range(0, argsCount).Select(j => $"{data.ArgName}{j}"))});");
        }

        private void GenerateOverrideWithParamsParameter(SuccessfulParamsCandidate paramsCandidate, DerivedData data)
        {
            if (!paramsCandidate.HasParams)
            {
                return;
            }
            _sourceBuilder.AppendLine();
            GenerateMethodHeaderWithArguments(data, data.FixArguments.Append($"params {data.SpanArgumentType}[] {data.ArgName}"));
            GenerateBodyWithParamsParameter(data);
            _sourceBuilder.CloseBlock();
        }

        private void GenerateBodyWithParamsParameter(DerivedData data)
        {
            GenerateSpanVariableForParamsArgument(data);
            GenerateCallOriginalMethod(data);
        }

        /// <summary>
        /// var {argsSpan} = new global::System.ReadOnlySpan<{T}>({args});
        /// </summary>
        private void GenerateSpanVariableForParamsArgument(DerivedData data)
        {
            var variableDeclaration = SimpleVarDeclaration(
                VariableDeclarator(
                    Identifier(data.ArgNameSpan),
                    null,
                    EqualsValueClause(NewReadOnlySpanOfTWithArgs(data.SpanArgumentType, data.ArgName))));
            _sourceBuilder.AppendBlockLine(variableDeclaration);
        }

        /// <summary>
        /// new global::System.ReadOnlySpan&lt;T&gt;(argName)
        /// </summary>
        private static ObjectCreationExpressionSyntax NewReadOnlySpanOfTWithArgs(string spanArgumentType, string argName)
        {
            return ObjectCreationExpression(
                ToGloballyQualifiedName("System", GenericName(Identifier("ReadOnlySpan"), OneTypeArgument(spanArgumentType))),
                Arguments(IdentifierName(argName)),
                null);
        }

        /// <summary>
        /// {argumentTypeName}
        /// </summary>
        private static TypeArgumentListSyntax OneTypeArgument(string argumentTypeName)
        {
            return TypeArgumentList(SingletonSeparatedList(ParseTypeName(argumentTypeName)));
        }

        /// <summary>
        /// {typeParameterName}
        /// </summary>
        private static TypeParameterListSyntax OneTypeParameter(string typeParameterName)
        {
            return TypeParameterList(SingletonSeparatedList(TypeParameter(typeParameterName)));
        }

        /// <summary>
        /// {arg} (In argument list)
        /// </summary>
        private static ArgumentListSyntax Arguments(ExpressionSyntax arg)
        {
            return ArgumentList(SingletonSeparatedList(Argument(arg)));
        }

        /// <summary>
        /// <code>ref {arg}</code>
        /// or
        /// <code>in {arg}</code>
        /// or
        /// <code>out {arg}</code>
        /// </summary>
        /// <exception cref="ArgumentOutOfRangeException">not None, ref, in or out.</exception>
        private static ArgumentSyntax QualifiedArgument(ExpressionSyntax arg, SyntaxKind syntaxKind = SyntaxKind.None)
        {
            return syntaxKind switch
            {
                SyntaxKind.None => Argument(arg),
                SyntaxKind.RefKeyword or
                SyntaxKind.OutKeyword or
                SyntaxKind.InKeyword => Argument(default, Token(syntaxKind), arg),
                _ => throw new ArgumentOutOfRangeException(nameof(syntaxKind)),
            };
        }

        /// <summary>
        /// {arg0}, {arg1}, {arg2}
        /// </summary>
        private static ArgumentListSyntax Arguments(IEnumerable<ArgumentSyntax> args)
        {
            return ArgumentList(SeparatedList(args));
        }

        private static QualifiedNameSyntax ToGloballyQualifiedName(string qualifier, SimpleNameSyntax nameSyntax)
        {
            return QualifiedName(
                        GlobalNameSyntax(qualifier), nameSyntax);
        }

        /// <summary>
        /// global::{parts[0]}.{parts[1]}.{parts[2]}
        /// </summary>
        private static ExpressionSyntax GlobalMemberAccessChain(
            string[] parts)
        {
            return MemberAccessChain(parts, isGlobal: true);
        }

        /// <summary>
        /// {parts[0]}.{parts[1]}.{parts[2]}
        /// </summary>
        private static ExpressionSyntax MemberAccessChain(
            string[] parts, bool isGlobal = false)
        {
            ExpressionSyntax current = isGlobal
                ? GlobalNameSyntax(parts[0])
                : IdentifierName(parts[0]);
            for (int i = 1; i < parts.Length; i++)
            {
                current = MemberAccessExpression(
                    SyntaxKind.SimpleMemberAccessExpression,
                    current,
                    IdentifierName(parts[i]));
            }
            return current;
        }

        /// <summary>
        /// global::{qualifier}
        /// </summary>
        private static AliasQualifiedNameSyntax GlobalNameSyntax(string qualifier)
        {
            return AliasQualifiedName(
                IdentifierName(Token(SyntaxKind.GlobalKeyword)),
                IdentifierName(qualifier));
        }

        /// <summary>
        /// var {varDeclarator}
        /// </summary>
        private static VariableDeclarationSyntax SimpleVarDeclaration(VariableDeclaratorSyntax varDeclarator)
        {
            return VariableDeclaration(VarIdentifier(), SingletonSeparatedList(varDeclarator));
        }

        /// <summary>
        /// var
        /// </summary>
        private static IdentifierNameSyntax VarIdentifier()
        {
            return IdentifierName(Identifier("var"));
        }

        private void GenerateArgumentsClasses()
        {
            for (int i = 1; i <= _maxOverridesMax; i++)
            {
                _sourceBuilder.AppendLine();
                CreateArguments(_sourceBuilder, i);
            }
        }

        /// <summary>
        /// return Format<{T}>({format}, {argsSpan})
        /// </summary>
        private void GenerateCallOriginalMethod(DerivedData data)
        {
            SimpleNameSyntax methodName = data.TypeArguments.Count > 0
                ? GenericName(Identifier(data.MethodName), TypeArgumentList(SeparatedList(GenerateInvocationTypeArguments(data))))
                : IdentifierName(data.MethodName);
            SyntaxNode invocationExpression = InvocationExpression(
                methodName,
                ArgumentList(SeparatedList(GenerateInvocationArguments(data))));
            invocationExpression = AddReturnStatement(data.ReturnsKind, invocationExpression);
            _sourceBuilder.AppendBlockLine(invocationExpression);
        }

        /// <summary>
        /// <code>Format()</code> 
        /// or
        /// <code>return Format()</code>
        /// or
        /// <code>return ref Format()</code>
        /// </summary>
        private static SyntaxNode AddReturnStatement(ReturnKind returnKind, SyntaxNode invocationExpression)
        {
            if (returnKind == ReturnKind.ReturnsRef)
            {
                invocationExpression = RefExpression((ExpressionSyntax)invocationExpression);
            }
            if (returnKind != ReturnKind.ReturnsVoid)
            {
                invocationExpression = ReturnStatement((ExpressionSyntax)invocationExpression);
            }

            return invocationExpression;
        }

        private IEnumerable<TypeSyntax> GenerateInvocationTypeArguments(DerivedData data)
        {
            foreach (var item in data.TypeArguments)
            {
                yield return IdentifierName(item);
            }
        }

        private IEnumerable<ArgumentSyntax> GenerateInvocationArguments(DerivedData data)
        {
            foreach (var item in data.ParameterInfos)
            {
                var argument = Argument(IdentifierName(item.Name));

                switch (item.GetPassParameterModifier())
                {
                    case RefKind.Ref:
                        argument = argument.WithRefKindKeyword(Token(SyntaxKind.RefKeyword));
                        break;
                    case RefKind.Out:
                        argument = argument.WithRefKindKeyword(Token(SyntaxKind.OutKeyword));
                        break;
                    case RefKind.In:
                        argument = argument.WithRefKindKeyword(Token(SyntaxKind.InKeyword));
                        break;
                    default:
                        break;
                }

                yield return argument;
            }
            var argSpan = Argument(IdentifierName(data.ArgNameSpanInput));
            yield return argSpan;
        }

        private static void CreateArguments(SourceBuilder sb, int length)
        {
            var typeName = Identifier($"Arguments{length}");
            var arguments = StructDeclaration(
                attributeLists: InlineArray(length),
                modifiers: TokenList(Token(SyntaxKind.FileKeyword)),
                identifier: typeName,
                typeParameterList: OneTypeParameter("T"),
                baseList: default,
                constraintClauses: default,
                members: ArgumentsTypeMembers(typeName, length));
            arguments = arguments.NormalizeWhitespace();
            MemberDeclarationSyntax oldNode = arguments.Members[0];
            var leadingT = oldNode.GetTrailingTrivia();
            arguments = arguments.ReplaceNode(
                oldNode,
                oldNode.WithTrailingTrivia(leadingT.Add(CarriageReturnLineFeed))
                );
            sb.AppendBlockLine(arguments, false);
            /*
            sb.Attribute($"System.Runtime.CompilerServices.InlineArray({length})");
            sb.GenericStruct($"Arguments{length}", "T");
            sb.Field("T", "arg0");
            sb.AppendLine();
            sb.Constructor(Enumerable.Range(0, length).Select(e => $"T value{e}"));
            sb.AppendLine($"arg0 = value0;");
            for (int i = 1; i < length; i++)
            {
                sb.AppendLine($"this[{i}] = value{i};");
            }
            sb.CloseBlock();
            sb.CloseBlock();*/
        }

        private static SyntaxList<MemberDeclarationSyntax> ArgumentsTypeMembers(
            SyntaxToken typeName,
            int argumentsCount)
        {
            return List(
                new MemberDeclarationSyntax[]{
                    FieldDeclaration(
                        VariableDeclaration(
                            IdentifierName("T"))
                        .WithVariables(
                            SingletonSeparatedList(
                                VariableDeclarator(
                                    Identifier("arg0")))))
                    .WithModifiers(
                        TokenList(
                            Token(SyntaxKind.PublicKeyword))),
                    ConstructorDeclaration(typeName)
                    .WithModifiers(
                        TokenList(
                            Token(SyntaxKind.PublicKeyword)))
                    .WithParameterList(
                        ParameterList(SeparatedList<ParameterSyntax>(
                            ArgumentsTypeCtorArguments(argumentsCount))))
                    .WithBody(
                        Block(
                            ArgumentsTypeCtorBody(argumentsCount))) });
        }

        private static IEnumerable<ParameterSyntax>? ArgumentsTypeCtorArguments(int argumentsCount)
        {
            for (int i = 0; i < argumentsCount; i++) {
                yield return Parameter(Identifier($"value{i}"))
                    .WithType(IdentifierName("T"));
            }
        }

        private static IEnumerable<StatementSyntax> ArgumentsTypeCtorBody(int argumentsCount)
        {
            yield return ExpressionStatement(
                    AssignmentExpression(
                        SyntaxKind.SimpleAssignmentExpression,
                        IdentifierName("arg0"),
                        IdentifierName("value0")));
            for (int i = 1; i < argumentsCount; i++)
            {
                yield return ExpressionStatement(
                    AssignmentExpression(
                        SyntaxKind.SimpleAssignmentExpression,
                        ElementAccessExpression(ThisExpression())
                        .WithArgumentList(Indexer(SimpleLiteral(i))),
                        IdentifierName($"value{i}")));
            }
        }

        private static BracketedArgumentListSyntax Indexer(ExpressionSyntax expressionSyntax)
        {
            return BracketedArgumentList(
                SingletonSeparatedList(
                    Argument(expressionSyntax)));
        }

        private static SyntaxList<AttributeListSyntax> InlineArray(int length)
        {
            return SingletonList<AttributeListSyntax>(
                AttributeList(
                    SingletonSeparatedList<AttributeSyntax>(
                        Attribute(
                            QualifiedName(
                                QualifiedName(
                                    QualifiedName(
                                        AliasQualifiedName(
                                            IdentifierName(
                                                Token(SyntaxKind.GlobalKeyword)),
                                            IdentifierName("System")),
                                        IdentifierName("Runtime")),
                                    IdentifierName("CompilerServices")),
                                IdentifierName("InlineArray")))
                        .WithArgumentList(
                            AttributeArgumentList(
                                SingletonSeparatedList<AttributeArgumentSyntax>(
                                    AttributeArgument(
                                        LiteralExpression(
                                            SyntaxKind.NumericLiteralExpression,
                                            Literal(length)))))))));
        }

        private static void AddNamespace(SourceBuilder sb, INamedTypeSymbol typeInfo)
        {
            if (typeInfo.ContainingNamespace.IsGlobalNamespace)
                return;

            /*var name = ParseName(SemanticHelpers.GetNameSpaceNoGlobal(typeInfo));
            var @namespace = NamespaceDeclaration(name);
            sb.AppendTrivia(@namespace);*/

            sb.Namespace(SemanticHelpers.GetNameSpaceNoGlobal(typeInfo));
        }

        private static void AddNamespaceCloseBlock(SourceBuilder sb, INamedTypeSymbol typeInfo)
        {
            if (typeInfo.ContainingNamespace.IsGlobalNamespace)
                return;

            sb.CloseBlock();
        }
    }

    public class AddReturn : CSharpSyntaxVisitor<FieldDeclarationSyntax>
    {
        public override FieldDeclarationSyntax? VisitFieldDeclaration(FieldDeclarationSyntax node)
        {
            return base.VisitFieldDeclaration(node);
        }
    }
}
