using System;
using System.Collections.Generic;
using System.Text;
using Foxy.Params.SourceGenerator.Data;

namespace Foxy.Params.SourceGenerator.Helpers;

internal partial class SourceBuilder
{
    private readonly StringBuilder _builder = new();
    public string Intend { get; set; } = "    ";
    private int _intendLevel = 0;
    public Stack<string> _scope = new Stack<string>();

    public override string ToString()
    {
        return _builder.ToString();
    }

    public void AddNamespaceHeader(string name)
    {
        AddLineInternal($"namespace {name}");
    }

    public void AddClassHeader(string name)
    {
        AddLineInternal($"partial class {name}");
    }

    public void AddBlock(Action<SourceBuilder> buidler)
    {
        OpenBlock();
        buidler(this);
        CloseBlock();
    }

    public void AddBlock<TArg1>(Action<SourceBuilder, TArg1> buidler, in TArg1 arg1)
    {
        OpenBlock();
        buidler(this, arg1);
        CloseBlock();
    }

    public void AddNamedBlock<TArg1>(
        string name,
        Action<SourceBuilder, TArg1> buidler,
        in TArg1 arg1)
    {
        PushScope(name);
        AddBlock(buidler, arg1);
        PopScope();
    }

    public void AddGenericStruct(string name, string genericParam1)
    {
        AddLineInternal($"file struct {name}<{genericParam1}>");
    }

    public void AddConstructorHeader(IEnumerable<string> args)
    {
        AddIntend();
        string className = _scope.Peek();
        _builder.Append($"public {className}(");
        AddCommaSeparatedList(args);
        _builder.AppendLine(")");
    }

    internal void Method(
        string name,
        IEnumerable<string> args,
        bool isStatic,
        string returnType,
        List<string> typeArguments,
        List<TypeConstrainInfo> typeConstraintsList)
    {
        AddIntend();
        _builder.Append("public");
        if (isStatic)
        {
            _builder.Append(" static");

        }
        _builder.Append(" ").Append(returnType);
        _builder.Append($" {name}");
        if (typeArguments.Count > 0)
        {
            _builder.Append($"<");
            AddCommaSeparatedList(typeArguments);
            _builder.Append($">");
        }
        _builder.Append($"(");
        AddCommaSeparatedList(args);
        _builder.AppendLine(")");
        AddTypeConstraints(typeConstraintsList);
    }

    public void Attribute(string name)
    {
        this.AppendV3($"[global::{name}]");
    }

    public void Field(string type, string name)
    {
        this.AppendV3($"public {type} {name};");
    }

    public void AutoGeneratedComment()
    {
        AddLineInternal("// <auto-generated />");
    }

    public void NullableEnable()
    {
        AddLineInternal("#nullable enable");
    }

    public void CloseBlock()
    {
        DecreaseIntend();
        AddLineInternal("}");
    }

    public void AppendLine()
    {
        _builder.AppendLine();
    }

    public void OpenBlock()
    {
        AddLineInternal("{");
        IncreaseIntend();
    }

    private void IncreaseIntend()
    {
        _intendLevel++;
    }
    private void PushScope(string scope)
    {
        _scope.Push(scope);
    }

    private void PopScope()
    {
        _scope.Pop();
    }

    private void DecreaseIntend()
    {
        _intendLevel--;
    }

    public SourceLine StartLine()
    {
        return new SourceLine(this);
    }

    public void Clear()
    {
        _intendLevel = 0;
        _builder.Clear();
        _scope.Clear();
    }

    public readonly ref struct SourceLine
    {
        private readonly SourceBuilder _builder;

        public SourceLine(SourceBuilder builder)
        {
            _builder = builder;
            _builder.AddIntend();
        }

        public void Returns()
        {
            _builder.AppendInternal("return ");
        }

        public void AddSegment(string segment)
        {
            _builder.AppendInternal(segment);
        }

        public void AddCommaSeparatedList(IEnumerable<string> elements)
        {
            _builder.AddCommaSeparatedList(elements);
        }

        public void EndLine()
        {
            _builder.AppendLineInternal(";");
        }
    }

    private void AppendLineInternal(string text)
    {
        _builder.AppendLine(text);
    }

    private void AppendInternal(string text)
    {
        _builder.Append(text);
    }

    private void AddTypeConstraints(List<TypeConstrainInfo> typeConstraintsList)
    {
        if (typeConstraintsList.Count <= 0)
            return;

        IncreaseIntend();
        foreach (var typeConstraints in typeConstraintsList)
        {
            AddIntend();
            _builder.Append($"where {typeConstraints.Type} : ");
            AddCommaSeparatedList(typeConstraints.Constraints);
            _builder.AppendLine();
        }
        DecreaseIntend();
    }

    private void AddLineInternal(string text)
    {
        AddIntend();
        _builder.AppendLine(text);
    }

    private void AddIntend()
    {
        for (int i = 0; i < _intendLevel; i++)
        {
            _builder.Append(Intend);
        }
    }

    private void AddCommaSeparatedList(IEnumerable<string> args)
    {
        _builder.AppendJoin(", ", args);
    }

    internal void AppendV2(FormattableString interpolatedString)
    {
        AddIntend();
        _builder.AppendFormat(interpolatedString.Format, interpolatedString.GetArguments());
    }

    private void AppendFormatted<T>(T? t)
    {
        if (t is not null)
        {
            _builder.Append(t.ToString());
        }
    }

    private void Append(string arg)
    {
        _builder.Append(arg);
    }

    private void Append(int arg)
    {
        _builder.Append(arg);
    }

    private void EnsureCapacity(int capacity)
    {
        _builder.EnsureCapacity(capacity);
    }

    internal void AppendLineV1(string v)
    {
        AddIntend();
        _builder.AppendLine(v);
    }
}
